<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-U7APJPA" failures="0" tests="2" name="com.qa.testcases.databricks.compute.TC_CMP_38" time="214.659" errors="1" timestamp="08 Aug 2022 08:32:44 GMT" skipped="1">
  <testcase classname="com.qa.testcases.databricks.compute.TC_CMP_38" name="TC_Compute_38_verifyRunningTabJobs" time="0.046">
    <skipped/>
  </testcase> <!-- TC_Compute_38_verifyRunningTabJobs -->
  <testcase classname="com.qa.testcases.databricks.compute.TC_CMP_38" name="beforeClass" time="214.613">
    <error message="Execution failed on all of 2 retries" type="java.lang.RuntimeException">
      <![CDATA[java.lang.RuntimeException: Execution failed on all of 2 retries
at com.qa.utils.actions.RetryExecuter.retry(RetryExecuter.java:59)
at com.qa.utils.actions.RetryExecuter.run(RetryExecuter.java:27)
at com.qa.scripts.Login.loginToApp(Login.java:64)
at com.qa.base.BaseClass.beforeClass(BaseClass.java:87)
at jdk.internal.reflect.GeneratedMethodAccessor48.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:168)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- beforeClass -->
</testsuite> <!-- com.qa.testcases.databricks.compute.TC_CMP_38 -->
